#!/usr/bin/env bash
# scripts/gen_lua_embed.sh
# Generates src/lua_stdlib_embed.hpp from src/lua-stdlib/*.lua files
# Usage: bash scripts/gen_lua_embed.sh
# Run from the project root directory.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
OUT="$PROJECT_ROOT/src/lua_stdlib_embed.hpp"

cat > "$OUT" << 'HEADER'
// Auto-generated by scripts/gen_lua_embed.sh — do not edit manually
// Run: bash scripts/gen_lua_embed.sh to regenerate
#pragma once
#include <string_view>

namespace mcpplibs::xpkg::detail {
HEADER

embed_file() {
    local varname="$1"
    local filepath="$2"
    echo "" >> "$OUT"
    echo "inline constexpr std::string_view ${varname} = R\"__LUA__(" >> "$OUT"
    cat "$filepath" >> "$OUT"
    printf ")__LUA__\";\n" >> "$OUT"
}

embed_file "prelude_lua"    "$PROJECT_ROOT/src/lua-stdlib/prelude.lua"
embed_file "log_lua"        "$PROJECT_ROOT/src/lua-stdlib/xim/libxpkg/log.lua"
embed_file "pkginfo_lua"    "$PROJECT_ROOT/src/lua-stdlib/xim/libxpkg/pkginfo.lua"
embed_file "system_lua"     "$PROJECT_ROOT/src/lua-stdlib/xim/libxpkg/system.lua"
embed_file "xvm_lua"        "$PROJECT_ROOT/src/lua-stdlib/xim/libxpkg/xvm.lua"
embed_file "utils_lua"      "$PROJECT_ROOT/src/lua-stdlib/xim/libxpkg/utils.lua"

cat >> "$OUT" << 'FOOTER'

} // namespace mcpplibs::xpkg::detail
FOOTER

echo "Generated: $OUT"
